version: '3'
services:
  mariadb:
    ports:
      - 3306:3306
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=qwer1234
      - MARIADB_DATABASE=setjetting
      - innodb_force_recovery=1
    volumes:
      - ./db:/var/lib/mysql
